name: echo_guide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.3.0
  firebase_core: ^2.30.1
  flutter_tts: ^3.8.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.3 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
